<?php
/**
 * @file
 * Code for the Bibsdb SEO feature.
 */

include_once 'bibsdb_seo.features.inc';


/**
 * Implements hook_node_presave. 
 * Changes xmlsitemap settings for pages with tag inspirationsliste
 * 
 * @param $node
 */
function bibsdb_seo_node_presave($node) {

  // Pages of with taxonomy term "Inspirationsliste" must be excluded from the xmlsitemap
  if ('ding_page' == $node->type) {
    $tid = 61;
    $wrapper = entity_metadata_wrapper('node', $node);

    // Set the defaults
    $node->xmlsitemap['status'] = 1;
    $node->xmlsitemap['status_override'] = 0;

    // Change if inspirationsliste
    foreach ($wrapper->field_ding_page_tags->getIterator() as $delta => $term_wrapper) {
      if ( $term_wrapper->getIdentifier() == $tid) {
        $node->xmlsitemap['status'] = 0;
        $node->xmlsitemap['status_override'] = 1;
      }
    } 
  }
}


/**
 * Implements hook_pathauto_alias_alter().
 * Change the pathauto alias for pages with tag "inspirationsliste"
 */

function bibsdb_expose_pathauto_alias_alter(&$alias, array &$context) {

  $tid = 61;

  // Limit to node entity type
  if ($context['module'] == 'node') {
    $node = $context['data']['node'];
    $wrapper = entity_metadata_wrapper('node', $node);

    // Limit to ding_pages that is tagged with "inspirationsliste"
    if ($node->type == 'ding_page') {
      foreach ($wrapper->field_ding_page_tags->getIterator() as $delta => $term_wrapper) {
        if ( $term_wrapper->getIdentifier() == $tid) {
          $alias = str_replace('indhold/', 'dbcliste/', $alias);
        }
      }
    }
  }
}
